### ISSUE TITLE
0 workflow runs to be deleted

### ISSUE THREAD

**Issue by lolollllo** [lolollllo/discord-portable-player#10]
WORKFLOW FILE
```yml
name: Clean Workflow Logs

on:
  workflow_dispatch:
    inputs:
      days_old:
        description: "The amount of days old to delete"
        default: "7"
        required: false

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v1
        with:
          token: ${{ secrets.gity_token }}
          owner: lolollllo
          repo: discord-portable-player
          days_old: ${{ github.event.inputs.days_old }}
```

![image](https://user-images.githubusercontent.com/99907738/174240057-0e13be33-ba9d-4690-af15-1de33ec500cf.png)
![image](https://user-images.githubusercontent.com/99907738/174240166-110d634f-3012-4aa8-9037-8d97d1ecb27a.png)
